<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "management_theme"
 *
 * Auto generated by Extension Builder 2020-06-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Theme Management',
    'description' => 'Frontend Theme of Management.',
    'category' => 'plugin',
    'author' => 'Nirmalya Mondal',
    'author_email' => 'nirmalya.mondal@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
